apiVersion: v1
kind: Service
metadata:
  name: app-satc-traffic-router
  namespace: ##K8S_NAMESPACE##
  labels:
    app: satc
spec:
  type: ClusterIP
  selector:
    app: satc
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
