apiVersion: v1
kind: Service
metadata:
  name: app-satc
  namespace: ##K8S_NAMESPACE##
  labels:
    app: satc
spec:
  type: ClusterIP
  selector:
    app: satc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
